### ISSUE TITLE
Tests using true_b fail to compile in 1.1.8

### ISSUE THREAD

**Issue by claremacrae** [boost-ext/ut#397]
## Expected Behavior

That this code compiles:

```cpp
        catch (const std::exception& e)
        {
            expect(approvalMissingExceptionReceived == true_b)
                << "Unexpected exception received: " << e.what();
        }
```

## Actual Behavior

Compiler error:

```
.../ApprovalTests.cpp/tests/UT_Tests/UTApprovalTestTests.cpp:34:56: error: use of undeclared identifier 'true_b'
            expect(approvalMissingExceptionReceived == true_b)
```

## Steps to Reproduce the Problem

With v 1.1.7:

- write a test using the following:

```cpp
expect(false_b == true_b);
```

With v1.1.8:

- Compile that test, and observe it fail to compile

## Specifications

  - Version: 1.1.7
  - Platform: macOS 10.15.7
  - Subsystem:

```
/opt/local/bin/clang-mp-9.0 --version
clang version 9.0.1 
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-9.0/bin
```

**Comment by krzysztof-jusiak** [comment]
Thanks, @claremacrae for reporting it.

`true_b` and `false_b` aren't part of the newest ut anymore, though.
Instead, a `named ""_b` is being used for better clarity.

Example
```cpp
expect("named"_b == not "named"_b);
```

Full code
> https://godbolt.org/z/b68W7K

**Comment by claremacrae** [comment]
Thanks for the reply.

I really don't understand that new code at all... I don't know what purpose "named" serves - and I can't see the benefit of it...

Godbolt shows the run-time answer is this, so the test output doesn't not contain the word "named" so it is not conveying any useful information to the user:

`<source>:5:FAILED [true == not true]`

Previously the code stated intent, by including the words `true` or `false` in the expectation... OK, needing to add `_b` at the end was non-obvious faff, but at least the presence of `true` or `false` showed what the result was supposed to be.

But, given that this is what the code now does, please could the README for the 1.1.8 be modified so that this is described as a breaking change, and so that it explains to users updating to 1.1.8 (or newer) what they need to do to fix the code.

(FWIW I changed mine to just use `== true` instead, so it still conveys intent...)

**Comment by krzysztof-jusiak** [comment]
Thanks for your valuable feedback, @claremacrae.

I agree that the name should be printed instead. I consider that to be a bug fixed by
* https://github.com/boost-ext/ut/pull/400.

Now, https://godbolt.org/z/b68W7K will show

```
<source>:5:FAILED [named == not named]
```
or whatever the name is being used.

I also updated the release notes for 1.1.8 and added the breaking change
* https://github.com/boost-ext/ut/releases/tag/v1.1.8

Finally, just some thoughts about the reasoning behind changing the behaviour.
I personally believe that `true_b == false_b` is kinda an artificial use case which can be used for testing but it's not really a real-life example. 

Instead, I'd consider the following a more expressive

```
expect(optional.has_value() == true_b); // true_b not that useful here
expect(optional.has_value() == true); // true not that useful here
expect(optional.has_value()); // okay, implicit
expect(has_value == "optional should not be empty"_b); // okay, explicit/expressive
```

Thanks again
