### ISSUE TITLE
Errors popped up for Visual Studio 16.10 Preview 3

### ISSUE THREAD

**Issue by Sebanisu** [boost-ext/ut#441]
I'm posting this because I'm not sure if it's a problem with Visual Studio or Boost.ut or if it's me.
## Expected Behavior
These worked in the 16.9.x versions of Visual Studio.
## Actual Behavior
Errors popped up for Visual Studio 16.10 Preview 3
## Steps to Reproduce the Problem

  1. Install Visual Studio 16.10 Preview 3
  1. Try to compile
  1. Error

## Specifications

  - Version: boost.ut trunk
  - Platform: Windows 10 x64
  - Subsystem: ?

```shell
====================[ Build | all | Debug Windows ]=============================
"C:\Program Files\JetBrains\CLion 2020.2\bin\cmake\win\bin\cmake.exe" --build D:\dev\ToolsLibrary\cmake-build-debug-windows --target all
Scanning dependencies of target ToolsLibrary_random_test
[  7%] Building CXX object tests/src/CMakeFiles/ToolsLibrary_random_test.dir/random_test.cpp.obj
random_test.cpp
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): error C3378: a declaration can be exported only from a module interface unit
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): error C2230: could not find module 'boost.ut'
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(10): error C3378: a declaration can be exported only from a module interface unit
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(10): error C7635: a module import declaration cannot appear in an 'export' declaration sequence
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(16): warning C5244: '#include <ciso646>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <ciso646>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(16): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(55): warning C5244: '#include <array>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <array>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(55): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(56): warning C5244: '#include <iostream>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <iostream>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(56): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(57): warning C5244: '#include <sstream>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <sstream>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(57): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(58): warning C5244: '#include <string_view>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <string_view>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(58): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(60): warning C5244: '#include <vector>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <vector>;'.
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(60): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(70): error C3378: a declaration can be exported only from a module interface unit
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(9): warning C5244: '#include <algorithm>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <algorithm>;'.
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(9): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(10): warning C5244: '#include <cassert>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <cassert>;'.
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(10): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(11): warning C5244: '#include <numeric>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <numeric>;'.
D:\dev\ToolsLibrary\src\tl/algorithm.hpp(11): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
D:\dev\ToolsLibrary\src\tl/random.hpp(8): warning C5244: '#include <random>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <random>;'.
D:\dev\ToolsLibrary\src\tl/random.hpp(8): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): note: see module 'boost.ut' declaration
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2019\Preview\VC\Tools\MSVC\1429~1.300\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30035\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30035\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by Sebanisu** [comment]
if I enable /Wv:18 it gets rid of some of these lines.

```shell
====================[ Build | all | Debug Windows ]=============================
"C:\Program Files\JetBrains\CLion 2020.2\bin\cmake\win\bin\cmake.exe" --build D:\dev\ToolsLibrary\cmake-build-debug-windows --target all
[  7%] Building CXX object tests/src/CMakeFiles/ToolsLibrary_random_test.dir/random_test.cpp.obj
random_test.cpp
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): error C3378: a declaration can be exported only from a module interface unit
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(9): error C2230: could not find module 'boost.ut'
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(10): error C3378: a declaration can be exported only from a module interface unit
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(10): error C7635: a module import declaration cannot appear in an 'export' declaration sequence
D:\dev\ToolsLibrary\cmake-build-debug-windows\_deps\ut-src\include\boost/ut.hpp(70): error C3378: a declaration can be exported only from a module interface unit
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1\2019\Preview\VC\Tools\MSVC\1429~1.300\bin\Hostx86\x86\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30035\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.29.30035\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
```

**Comment by Sebanisu** [comment]
if I switch `#include <boost/ut.hpp>` to `import boost.ut;` it's errors:
```shell
====================[ Build | all | Debug Windows ]=============================
"C:\Program Files\JetBrains\CLion 2020.2\bin\cmake\win\bin\cmake.exe" --build D:\dev\ToolsLibrary\cmake-build-debug-windows --target all
Scanning dependencies of target ToolsLibrary_random_test
[  7%] Building CXX object tests/src/CMakeFiles/ToolsLibrary_random_test.dir/random_test.cpp.obj
random_test.cpp
D:\dev\ToolsLibrary\tests\src\random_test.cpp(2): error C2230: could not find module 'boost.ut'
```

**Comment by Au-lit** [comment]
> if I switch `#include <boost/ut.hpp>` to `import boost.ut;` it's errors:
> 
> ```shell
> ====================[ Build | all | Debug Windows ]=============================
> "C:\Program Files\JetBrains\CLion 2020.2\bin\cmake\win\bin\cmake.exe" --build D:\dev\ToolsLibrary\cmake-build-debug-windows --target all
> Scanning dependencies of target ToolsLibrary_random_test
> [  7%] Building CXX object tests/src/CMakeFiles/ToolsLibrary_random_test.dir/random_test.cpp.obj
> random_test.cpp
> D:\dev\ToolsLibrary\tests\src\random_test.cpp(2): error C2230: could not find module 'boost.ut'
> ```

This is to be expected because MSVC requires a `.ixx`/`.cppm` file for the module. Unfortunately trying to make a `ut.cppm`/`ut.ixx` will still fail; trying to do:
```cpp
// ut.ixx
#include <boost/ut.hpp> 
```
for me emits 
```md
1>ut.ixx
1>Compilation...
1>ut.ixx
1>D:\Third-Party\ut\include\boost\ut.hpp(10,18): error C3674: the standard library module 'std' is not found
1>D:\Third-Party\ut\include\boost\ut.hpp(16,10): warning C5244: '#include <ciso646>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <ciso646>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
1>D:\Third-Party\ut\include\boost\ut.hpp(55,10): warning C5244: '#include <array>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <array>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
1>D:\Third-Party\ut\include\boost\ut.hpp(56,10): warning C5244: '#include <iostream>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <iostream>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
1>D:\Third-Party\ut\include\boost\ut.hpp(57,10): warning C5244: '#include <sstream>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <sstream>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
1>D:\Third-Party\ut\include\boost\ut.hpp(58,10): warning C5244: '#include <string_view>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <string_view>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
1>D:\Third-Party\ut\include\boost\ut.hpp(60,10): warning C5244: '#include <vector>' in the purview of module 'boost.ut' appears erroneous.  Consider moving that directive before the module declaration, or replace the textual inclusion with 'import <vector>;'.
1>D:\Third-Party\ut\include\boost\ut.hpp(9,8): message : see module 'boost.ut' declaration
```

**Comment by Au-lit** [comment]
I just tried to create an other file `ut.cppm` in a more intelligent than just including `<boost/ut.hpp>` in a `.cppm` and I got an internal compiler error...

**Comment by Au-lit** [comment]
Thinking about it it's quite logical that it said
> the standard library module 'std' is not found

because well the standard says nothing about it. An implementation is not in any way requiered to have a `std` module. For instance MSVC only provides 
- `std.regex`
- `std.filesystem`
- `std.memory`
- `std.threading`

and `std.core`. (See the [MS docs on consuming the C++ Standard Library as modules](https://docs.microsoft.com/en-us/cpp/cpp/modules-cpp?view=msvc-160#consume-the-c-standard-library-as-modules))

**Comment by Au-lit** [comment]
Oh and it seems that legacy imports are not yet implemented in the Microsoft C++ compiler but I _could_ be wrong...

**Comment by Sebanisu** [comment]
https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.10.0.pre.4.0 Preview 4 was released 5/18/2021 It does the same thing as Preview 3.

**Comment by go2sh** [comment]
I can confirm, that there is a regression between MVSC 14.28 (16.9) and MSVC 14.29 (16.10). MS enabled all c++20 features under the /std:c++latest switch. The docs say you can disable modules with /experimental:module- but that doesn't work either.

**Comment by go2sh** [comment]
I guess that options isn't available in msvc 14.29 any more :( So to "fix" that problem, it would be required to add another SWITCH to enable modules not only by feature macro. @krzysztof-jusiak Is that okay for you?

**Comment by krzysztof-jusiak** [comment]
Sure, I'm open to suggestions/solutions?

**Comment by Au-lit** [comment]
Sadly I don’t know how it could be implemented without a macro or a separate file...

**Comment by go2sh** [comment]
A Macro would be the way to go.

**Comment by Au-lit** [comment]
Well, the literal first thing you see when you come on this repo is "macro-free" so…
> C++ single header/single module, **macro-free** μ (micro)/Unit Testing Framework

**Comment by go2sh** [comment]
Technically there is already a macro in use, the modules feature test macro. ;-) But I see your point. But I guess there are two options going forward and this problem will happen with other compilers as well, if the compiler enables __cpp_modules with the -std=c++20 switch and the header is used in non module mode. 
1) Use one compiler defined value to check if the header is read in module or normal mode. 
2) Split up module definition and header file.

**Comment by Sebanisu** [comment]
Could maybe use cmake to generate a module header or a normal header. With like https://cmake.org/cmake/help/latest/command/configure_file.html you can insert values. Though it's probably easier to just set a macro in cmake and then check for it.

Kinda wish they had a built in c++20 macro to know if you were imported or included.

**Comment by go2sh** [comment]
I create a quick PR with a macro solutions. I guess a macro for features selection is okay and doesn't violate the macro free rule in terms of, that all testing code is macro free.
